name: Vanilla Gu
id: vanilla-gu
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:main
  singlelayer: false
  labels:
    maintainer: guztaver
  args:
    DEBIAN_FRONTEND: noninteractive

  modules:
  - name: init-setup
    type: shell
    commands:
    - lpkg --unlock
    - apt-get update

  - name: modules
    type: includes
    includes:
      - modules/61-setup-tailscale.yml
      - modules/62-setup-dotfiles.yml

  - name: cleanup
    type: shell
    commands:
    - apt-get autoremove -y
    - apt-get clean
    - lpkg --lock

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
